SCREEN_UPDATE:
  ds 1

ARROW_UPDATE:
  ds 1

ARROW_DIRECTION:
  ds 1

slotValuesStart:
slot1Value:
  ds 1

slot2Value:
  ds 1

slot3Value:
  ds 1

slot4Value:
  ds 1

slot5Value:
  ds 1
slotValuesEnd:

_PAD:
  ds 1

_PAD_PRESSED:
  ds 1

ARROW_X:
  ds 1

ARROW_Y:
  ds 1

ARROW_MIN_Y:
  ds 1

ARROW_MAX_Y:
  ds 1

ARROW_MIN_X:
  ds 1

ARROW_MAX_X:
  ds 1

ARROW_X_CHANGE:
  ds 1

ARROW_Y_CHANGE:
  ds 1

NO_BACK:
  ds 1

DISABLE_KEEP_SCORE:
  ds 1

SELECTION:
  ds 1

MENU:
  ds 1

CARD:
  ds 1

KEPT_DICE:
  ds 1

Seed:
  ds 3

RN:
  ds 5

ROLL_COUNT:
  ds 1

POSSIBLE_ONES:
  ds 1

POSSIBLE_TWOS:
  ds 1

POSSIBLE_THREES:
  ds 1

POSSIBLE_FOURS:
  ds 1

POSSIBLE_FIVES:
  ds 1

POSSIBLE_SIXES:
  ds 1

POSSIBLE_3KIND:
  ds 1

POSSIBLE_4KIND:
  ds 1

POSSIBLE_FULL:
  ds 1

POSSIBLE_SMALL:
  ds 1

POSSIBLE_LARGE:
  ds 1

POSSIBLE_YATZY:
  ds 1

POSSIBLE_CHANCE:
  ds 1
