SCREEN_UPDATE:
  ds 1

ARROW_UPDATE:
  ds 1

ARROW_DIRECTION:
  ds 1

slotValuesStart:
slot1Value:
  ds 1

slot2Value:
  ds 1

slot3Value:
  ds 1

slot4Value:
  ds 1

slot5Value:
  ds 1
slotValuesEnd:

_PAD:
  ds 1

_PAD_PRESSED:
  ds 1

ARROW_X:
  ds 1

ARROW_Y:
  ds 1

ARROW_MIN_Y:
  ds 1

ARROW_MAX_Y:
  ds 1

ARROW_MIN_X:
  ds 1

ARROW_MAX_X:
  ds 1

ARROW_X_CHANGE:
  ds 1

ARROW_Y_CHANGE:
  ds 1

NO_BACK:
  ds 1

DISABLE_KEEP_SCORE:
  ds 1

SELECTION:
  ds 1

MENU:
  ds 1

CARD:
  ds 1

KEPT_DICE:
  ds 1

Seed:
  ds 3

RN:
  ds 5

DISPLAY_TOTAL:
  ds 4

DISPLAY_SUBTOTAL:
  ds 3

DISPLAY_ONES:
  ds 2

DISPLAY_TWOS:
  ds 2

DISPLAY_THREES:
  ds 2

DISPLAY_FOURS:
  ds 2

DISPLAY_FIVES:
  ds 2

DISPLAY_SIXES:
  ds 2

DISPLAY_BONUS:
  ds 2

DISPLAY_3KIND:
  ds 2

DISPLAY_4KIND:
  ds 2

DISPLAY_FULL:
  ds 2

DISPLAY_SMALL:
  ds 2

DISPLAY_LARGE:
  ds 2

DISPLAY_YATZY:
  ds 2

DISPLAY_CHANCE:
  ds 2

ROLL_COUNT:
  ds 1

POSSIBLE_ONES:
  ds 1

POSSIBLE_TWOS:
  ds 1

POSSIBLE_THREES:
  ds 1

POSSIBLE_FOURS:
  ds 1

POSSIBLE_FIVES:
  ds 1

POSSIBLE_SIXES:
  ds 1

POSSIBLE_BONUS:
  ds 1

POSSIBLE_3KIND:
  ds 1

POSSIBLE_4KIND:
  ds 1

POSSIBLE_FULL:
  ds 1

POSSIBLE_SMALL:
  ds 1

POSSIBLE_LARGE:
  ds 1

POSSIBLE_YATZY:
  ds 1

POSSIBLE_CHANCE:
  ds 1

TOTAL:
  ds 2

SUBTOTAL:
  ds 1

LOWER_STATUS:
  ds 1

UPPER_STATUS:
  ds 1

DICE_STATUS:
  ds 1

GAME_FINISHED:
  ds 1