Dice0MapStart:
DB $01,$02,$03
DB $04,$05,$06
DB $07,$08,$09
Dice0MapEnd:

Dice1MapStart:
DB $0A,$0B,$0C
DB $0D,$0E,$0F
DB $10,$11,$12
Dice1MapEnd:

Dice2MapStart:
DB $13,$14,$15
DB $16,$17,$18
DB $19,$1A,$1B
Dice2MapEnd:

Dice3MapStart:
DB $1C,$1D,$1E
DB $1F,$20,$21
DB $22,$23,$24
Dice3MapEnd:

Dice4MapStart:
DB $25,$26,$27
DB $28,$29,$2A
DB $2B,$2C,$2D
Dice4MapEnd:

Dice5MapStart:
DB $2E,$2F,$30
DB $31,$32,$33
DB $34,$35,$36
Dice5MapEnd:

Dice6MapStart:
DB $37,$38,$39
DB $3A,$3B,$3C
DB $3D,$3E,$3F
Dice6MapEnd:

ArrowMapStart:
DB $40
ArrowMapEnd:

RollMapStart:
DB $00, $41,$42,$43
RollMapEnd:

KeepMapStart:
DB $00, $44, $45, $46
KeepMapEnd:

ScoreMapStart:
DB $00, $47, $48, $49
ScoreMapEnd:

OnesMapStart:
DB $00, $4A,$4B, $4C
OnesMapEnd:

TwosMapStart:
DB $00, $4D, $4E, $4F
TwosMapEnd:

ThreesMapStart:
DB $00, $50, $51, $52
ThreesMapEnd:

FoursMapStart:
DB $00, $53, $54, $55
FoursMapEnd:

FivesMapStart:
DB $00, $56, $57, $58
FivesMapEnd:

SixesMapStart:
DB $00, $59, $5A, $5B
SixesMapEnd:

BonusMapStart:
DB $00, $5C, $5D, $5E
BonusMapEnd:

ThreeKindMapStart:
DB $00, $5F, $60, $61
ThreeKindMapEnd:

FourKindMapStart:
DB $00, $62, $63, $64
FourKindMapEnd:

FullMapStart:
DB $00, $65, $66, $67
FullMapEnd:

SmallMapStart:
DB $00, $68, $69, $6A
SmallMapEnd:

LargeMapStart:
DB $00, $6B, $6C, $6D
LargeMapEnd:

YatzyMapStart:
DB $00, $6E, $6F, $70
YatzyMapEnd:

ChanceMapStart:
DB $00, $71, $72, $73
ChanceMapEnd:

RollsMapStart:
DB $00, $74, $75, $76
RollsMapEnd:

SubtotalMapStart:
DB $77, $78, $79, $7A
SubtotalMapEnd:

TotalMapStart:
DB $7B, $7C, $7D, $7E
TotalMapEnd:

VerticalBorderMapStart:
DB $7F
VerticalBorderMapEnd:

HorizontalBorderMapStart:
DB $80
HorizontalBorderMapEnd:

JunctionBLMapStart:
DB $81
JunctionBLMapEnd:

JunctionBMapStart:
DB $82
JunctionBMapEnd:

JunctionBRMapStart:
DB $83
JunctionBRMapEnd:

JunctionLMapStart:
DB $84
JunctionLMapEnd:

JunctionRMapStart:
DB $85
JunctionRMapEnd:

JunctionTLMapStart:
DB $86
JunctionTLMapEnd:

JunctionTRMapStart:
DB $87
JunctionTRMapEnd:

JunctionTMapStart:
DB $88
JunctionTMapEnd: