Dice0MapStart:
DB $01,$02,$02,$03
DB $04,$05,$05,$06
DB $04,$05,$05,$06
DB $07,$08,$08,$09
Dice0MapEnd:

Dice1MapStart:
DB $0A,$0B,$0B,$0C
DB $0D,$0E,$0F,$10
DB $0D,$11,$12,$10
DB $13,$14,$14,$15
Dice1MapEnd:

Dice2MapStart:
DB $16,$17,$18,$19
DB $1A,$1B,$1C,$1D
DB $1E,$1F,$1B,$20
DB $21,$22,$23,$24
Dice2MapEnd:

Dice3MapStart:
DB $25,$26,$27,$28
DB $29,$2A,$2B,$2C
DB $2D,$2B,$2E,$2F
DB $30,$31,$32,$33
Dice3MapEnd:

Dice4MapStart:
DB $34,$35,$36,$37
DB $38,$39,$3A,$3B
DB $3C,$3D,$3E,$3F
DB $40,$41,$42,$43
Dice4MapEnd:

Dice5MapStart:
DB $44,$45,$46,$47
DB $48,$49,$4A,$4B
DB $4C,$4A,$49,$4D
DB $4E,$4F,$50,$51
Dice5MapEnd:

Dice6MapStart:
DB $52,$53,$54,$55
DB $56,$57,$58,$59
DB $56,$57,$58,$59
DB $5A,$5B,$5C,$5D
Dice6MapEnd:

ArrowMapStart:
DB $5E
ArrowMapEnd:

RollMapStart:
DB $5F,$60,$61
RollMapEnd:

KeepMapStart:
DB $62, $63, $64
KeepMapEnd:

ScoreMapStart:
DB $65, $66, $67
ScoreMapEnd:

OnesMapStart:
DB $68,$69, $6A
OnesMapEnd:

TwosMapStart:
DB $6B, $6C, $6D
TwosMapEnd:

ThreesMapStart:
DB $6E, $6F, $70
ThreesMapEnd:

FoursMapStart:
DB $71, $72, $73
FoursMapEnd:

FivesMapStart:
DB $74, $75, $76
FivesMapEnd:

SixesMapStart:
DB $77, $78, $79
SixesMapEnd: